name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      run_job:
        required: false
        type: boolean
        description: Run Specific Job
      custom_message:
        required: true
        type: string
        description: Enter a custom message

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Exploring Workflow Dispatch Trigger"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Custom Message
        run: echo "${{ inputs.custom_message }}" 
